version: '3.8'
services:
  vault:
    image: hashicorp/vault:1.15
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    command: vault server -dev -dev-root-token-id=root
    volumes:
      - ./vault/service/service-setup.sh:/service-setup.sh
    entrypoint: ["/bin/sh", "/service-setup.sh"]
    networks:
      - vault-poc

  vault-client:
    image: python:3.10-slim
    container_name: vault-client
    user: root
    depends_on:
      - vault
    volumes:
      - ./vault/client:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "client-setup.sh"]
    networks:
      - vault-poc

networks:
  vault-poc:
    external: true