services:
  python-vault-client:
    image: python:3.8-alpine
    container_name: python-vault-client
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
    volumes:
      - ./python-app:/app
    working_dir: /app
    entrypoint: ["/bin/sh", "setup.sh"]
    networks:
      - vault-poc

networks:
  vault-poc:
    external: true
